### PR TITLE
Syntax Highlighting - CloudSlang Flavor

### PR DESCRIPTION
**Pull request by levice14**
Signed-off-by: Bonczidai Levente levente.bonczidai@hpe.com

### CODE REVIEW

**Comment by oritstone** [comment]
What about the `on_failure` keyword?
Are there additional CloudSlang keywords missing?

**Comment by levice14** [comment]
`on_failure` is not highlighted yet ( #5 ) do you think we should address it before merge?

**Comment by oritstone** [comment]
You can open an issue about it, and I will merge this PR
Is is the only keyword missing?

**Comment by levice14** [comment]
there is an issue for `on_failure`: #5 

I think this is the only keyword missing (not talking about keywords inside python scripts / expressions)

**Pull request merged**
