### PR TITLE
Update: op hierarchy changes

### LINKED ISSUE #80: Update: op hierarchy changes
https://github.com/CloudSlang/cloud-slang/issues/675

### PR DESCRIPTION
**Pull request by gituser173**
Fixes  #80

Signed-off-by: Claudiu Ban claudiu-laurian.ban@hpe.com

### CODE REVIEW

**Comment by levice14** [comment]
Please also handle:
- pay attention to snake case in java action
- update grammar (syntax highlight) to new keywords
- take into account the new keywords (gav, dependencies) -- maybe you can skip this for now - you can open an issue so we'll remember to add when the mechanism will be functional in the language

for feature details see: https://github.com/CloudSlang/cloud-slang/issues/675

**Comment by SamMarkowitz** [comment]
Also update readme.md

**Comment by gituser173** [comment]
@Bonczidai added #84

**Comment by levice14** [comment]
:+1:

**Pull request merged**
